### Listar pedidos
GET http://localhost:3002/pedidos

### Criar pedido
POST http://localhost:3002/pedidos
Content-Type: application/json

{
  "cliente_id": 1,
  "produtos": [
    {
      "produto_id": 2,
      "quantidade": 3
    }
  ]
}

### Buscar pedido por ID
GET http://localhost:3002/pedidos/1