services:
  produtos:
    build: ./produtos
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/produtos_db
    depends_on:
      postgres:
        condition: service_healthy

  pedidos:
    build: ./pedidos
    ports:
      - "3002:3002"
    environment:
      PRODUTOS_URL: http://produtos:3001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pedidos_db
    depends_on:
      postgres:
        condition: service_healthy
      produtos:
        condition: service_started

  clientes:
    build: ./clientes
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/clientes_db
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      PRODUTOS_URL: http://produtos:3001
      PEDIDOS_URL: http://pedidos:3002
      CLIENTES_URL: http://clientes:3003
    depends_on:
      - produtos
      - pedidos
      - clientes

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produtos_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: