### Criar cliente
POST http://localhost:3003/clientes
Content-Type: application/json

{
  "nome": "Luan",
  "sobrenome": "Luan Gabriel da Silva Freitas",
  "telefone": "44998163459",
  "email": "luan004@email.com"
}

### Buscar clientes
GET http://localhost:3003/clientes


### Buscar cliente por id
GET http://localhost:3003/clientes/2


### Buscar cliente inexistente
GET http://localhost:3003/clientes/999


### Criar cliente sem sobrenome (nome obrigatório)
POST http://localhost:3003/clientes
Content-Type: application/json

{
  "nome": "João"
}

### Criar cliente sem telefone (nome, sobrenome e email obrigatórios)
POST http://localhost:3003/clientes
Content-Type: application/json

{
  "nome": "João",
  "sobrenome": "Silva",
  "email": "joao@email.com"
}